// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushservice.proto

package com.xxx.pushservice.proto;

public interface PushReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PushReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientId = 1;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
