// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushservice.proto

package com.xxx.pushservice.proto;

public interface PushServicev2 {

    static final public int serviceId = 102;

    com.xxx.pushservice.proto.PushRes pushv2(com.xxx.pushservice.proto.PushReq req);
    static final public int pushv2MsgId = 1;

}

