// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: krpcmonitor.proto

package krpc.rpc.monitor.proto;

public interface ReportAlarmResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportAlarmRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 retCode = 1;</code>
   */
  int getRetCode();

  /**
   * <code>string retMsg = 2;</code>
   */
  String getRetMsg();
  /**
   * <code>string retMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getRetMsgBytes();
}
