// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: krpcmonitor.proto

package krpc.rpc.monitor.proto;

public interface ReportSystemInfoResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportSystemInfoRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 retCode = 1;</code>
   */
  int getRetCode();

  /**
   * <code>string retMsg = 2;</code>
   */
  java.lang.String getRetMsg();
  /**
   * <code>string retMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getRetMsgBytes();
}
