// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.xxx.userservice.proto;

/**
 * Protobuf type {@code HttpDownloadStaticRes}
 */
public  final class HttpDownloadStaticRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HttpDownloadStaticRes)
    HttpDownloadStaticResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HttpDownloadStaticRes.newBuilder() to construct.
  private HttpDownloadStaticRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HttpDownloadStaticRes() {
    retCode_ = 0;
    retMsg_ = "";
    downloadFile_ = "";
    autoDelete_ = "";
    attachment_ = 0;
    expire_ = 0;
    downloadStream_ = com.google.protobuf.ByteString.EMPTY;
    filename_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HttpDownloadStaticRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            retCode_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            retMsg_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            downloadFile_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            autoDelete_ = s;
            break;
          }
          case 40: {

            attachment_ = input.readInt32();
            break;
          }
          case 48: {

            expire_ = input.readInt32();
            break;
          }
          case 58: {

            downloadStream_ = input.readBytes();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            filename_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xxx.userservice.proto.UserServiceMetas.internal_static_HttpDownloadStaticRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xxx.userservice.proto.UserServiceMetas.internal_static_HttpDownloadStaticRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xxx.userservice.proto.HttpDownloadStaticRes.class, com.xxx.userservice.proto.HttpDownloadStaticRes.Builder.class);
  }

  public static final int RETCODE_FIELD_NUMBER = 1;
  private int retCode_;
  /**
   * <code>int32 retCode = 1;</code>
   */
  public int getRetCode() {
    return retCode_;
  }

  public static final int RETMSG_FIELD_NUMBER = 2;
  private volatile java.lang.Object retMsg_;
  /**
   * <code>string retMsg = 2;</code>
   */
  public java.lang.String getRetMsg() {
    java.lang.Object ref = retMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      retMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string retMsg = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRetMsgBytes() {
    java.lang.Object ref = retMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      retMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOWNLOADFILE_FIELD_NUMBER = 3;
  private volatile java.lang.Object downloadFile_;
  /**
   * <code>string downloadFile = 3;</code>
   */
  public java.lang.String getDownloadFile() {
    java.lang.Object ref = downloadFile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      downloadFile_ = s;
      return s;
    }
  }
  /**
   * <code>string downloadFile = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDownloadFileBytes() {
    java.lang.Object ref = downloadFile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      downloadFile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTODELETE_FIELD_NUMBER = 4;
  private volatile java.lang.Object autoDelete_;
  /**
   * <code>string autoDelete = 4;</code>
   */
  public java.lang.String getAutoDelete() {
    java.lang.Object ref = autoDelete_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      autoDelete_ = s;
      return s;
    }
  }
  /**
   * <code>string autoDelete = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAutoDeleteBytes() {
    java.lang.Object ref = autoDelete_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      autoDelete_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTACHMENT_FIELD_NUMBER = 5;
  private int attachment_;
  /**
   * <code>int32 attachment = 5;</code>
   */
  public int getAttachment() {
    return attachment_;
  }

  public static final int EXPIRE_FIELD_NUMBER = 6;
  private int expire_;
  /**
   * <code>int32 expire = 6;</code>
   */
  public int getExpire() {
    return expire_;
  }

  public static final int DOWNLOADSTREAM_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString downloadStream_;
  /**
   * <code>bytes downloadStream = 7;</code>
   */
  public com.google.protobuf.ByteString getDownloadStream() {
    return downloadStream_;
  }

  public static final int FILENAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object filename_;
  /**
   * <code>string filename = 8;</code>
   */
  public java.lang.String getFilename() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filename_ = s;
      return s;
    }
  }
  /**
   * <code>string filename = 8;</code>
   */
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (retCode_ != 0) {
      output.writeInt32(1, retCode_);
    }
    if (!getRetMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, retMsg_);
    }
    if (!getDownloadFileBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, downloadFile_);
    }
    if (!getAutoDeleteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, autoDelete_);
    }
    if (attachment_ != 0) {
      output.writeInt32(5, attachment_);
    }
    if (expire_ != 0) {
      output.writeInt32(6, expire_);
    }
    if (!downloadStream_.isEmpty()) {
      output.writeBytes(7, downloadStream_);
    }
    if (!getFilenameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, filename_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (retCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, retCode_);
    }
    if (!getRetMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, retMsg_);
    }
    if (!getDownloadFileBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, downloadFile_);
    }
    if (!getAutoDeleteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, autoDelete_);
    }
    if (attachment_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, attachment_);
    }
    if (expire_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, expire_);
    }
    if (!downloadStream_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, downloadStream_);
    }
    if (!getFilenameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, filename_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xxx.userservice.proto.HttpDownloadStaticRes)) {
      return super.equals(obj);
    }
    com.xxx.userservice.proto.HttpDownloadStaticRes other = (com.xxx.userservice.proto.HttpDownloadStaticRes) obj;

    boolean result = true;
    result = result && (getRetCode()
        == other.getRetCode());
    result = result && getRetMsg()
        .equals(other.getRetMsg());
    result = result && getDownloadFile()
        .equals(other.getDownloadFile());
    result = result && getAutoDelete()
        .equals(other.getAutoDelete());
    result = result && (getAttachment()
        == other.getAttachment());
    result = result && (getExpire()
        == other.getExpire());
    result = result && getDownloadStream()
        .equals(other.getDownloadStream());
    result = result && getFilename()
        .equals(other.getFilename());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RETCODE_FIELD_NUMBER;
    hash = (53 * hash) + getRetCode();
    hash = (37 * hash) + RETMSG_FIELD_NUMBER;
    hash = (53 * hash) + getRetMsg().hashCode();
    hash = (37 * hash) + DOWNLOADFILE_FIELD_NUMBER;
    hash = (53 * hash) + getDownloadFile().hashCode();
    hash = (37 * hash) + AUTODELETE_FIELD_NUMBER;
    hash = (53 * hash) + getAutoDelete().hashCode();
    hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
    hash = (53 * hash) + getAttachment();
    hash = (37 * hash) + EXPIRE_FIELD_NUMBER;
    hash = (53 * hash) + getExpire();
    hash = (37 * hash) + DOWNLOADSTREAM_FIELD_NUMBER;
    hash = (53 * hash) + getDownloadStream().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilename().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxx.userservice.proto.HttpDownloadStaticRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xxx.userservice.proto.HttpDownloadStaticRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HttpDownloadStaticRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HttpDownloadStaticRes)
      com.xxx.userservice.proto.HttpDownloadStaticResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxx.userservice.proto.UserServiceMetas.internal_static_HttpDownloadStaticRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxx.userservice.proto.UserServiceMetas.internal_static_HttpDownloadStaticRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxx.userservice.proto.HttpDownloadStaticRes.class, com.xxx.userservice.proto.HttpDownloadStaticRes.Builder.class);
    }

    // Construct using com.xxx.userservice.proto.HttpDownloadStaticRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      retCode_ = 0;

      retMsg_ = "";

      downloadFile_ = "";

      autoDelete_ = "";

      attachment_ = 0;

      expire_ = 0;

      downloadStream_ = com.google.protobuf.ByteString.EMPTY;

      filename_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xxx.userservice.proto.UserServiceMetas.internal_static_HttpDownloadStaticRes_descriptor;
    }

    @java.lang.Override
    public com.xxx.userservice.proto.HttpDownloadStaticRes getDefaultInstanceForType() {
      return com.xxx.userservice.proto.HttpDownloadStaticRes.getDefaultInstance();
    }

    @java.lang.Override
    public com.xxx.userservice.proto.HttpDownloadStaticRes build() {
      com.xxx.userservice.proto.HttpDownloadStaticRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xxx.userservice.proto.HttpDownloadStaticRes buildPartial() {
      com.xxx.userservice.proto.HttpDownloadStaticRes result = new com.xxx.userservice.proto.HttpDownloadStaticRes(this);
      result.retCode_ = retCode_;
      result.retMsg_ = retMsg_;
      result.downloadFile_ = downloadFile_;
      result.autoDelete_ = autoDelete_;
      result.attachment_ = attachment_;
      result.expire_ = expire_;
      result.downloadStream_ = downloadStream_;
      result.filename_ = filename_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xxx.userservice.proto.HttpDownloadStaticRes) {
        return mergeFrom((com.xxx.userservice.proto.HttpDownloadStaticRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xxx.userservice.proto.HttpDownloadStaticRes other) {
      if (other == com.xxx.userservice.proto.HttpDownloadStaticRes.getDefaultInstance()) return this;
      if (other.getRetCode() != 0) {
        setRetCode(other.getRetCode());
      }
      if (!other.getRetMsg().isEmpty()) {
        retMsg_ = other.retMsg_;
        onChanged();
      }
      if (!other.getDownloadFile().isEmpty()) {
        downloadFile_ = other.downloadFile_;
        onChanged();
      }
      if (!other.getAutoDelete().isEmpty()) {
        autoDelete_ = other.autoDelete_;
        onChanged();
      }
      if (other.getAttachment() != 0) {
        setAttachment(other.getAttachment());
      }
      if (other.getExpire() != 0) {
        setExpire(other.getExpire());
      }
      if (other.getDownloadStream() != com.google.protobuf.ByteString.EMPTY) {
        setDownloadStream(other.getDownloadStream());
      }
      if (!other.getFilename().isEmpty()) {
        filename_ = other.filename_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xxx.userservice.proto.HttpDownloadStaticRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xxx.userservice.proto.HttpDownloadStaticRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int retCode_ ;
    /**
     * <code>int32 retCode = 1;</code>
     */
    public int getRetCode() {
      return retCode_;
    }
    /**
     * <code>int32 retCode = 1;</code>
     */
    public Builder setRetCode(int value) {
      
      retCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 retCode = 1;</code>
     */
    public Builder clearRetCode() {
      
      retCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object retMsg_ = "";
    /**
     * <code>string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        retMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string retMsg = 2;</code>
     */
    public Builder setRetMsg(
        java.lang.String value) {
      if (value == null) value = "";
  
      retMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string retMsg = 2;</code>
     */
    public Builder clearRetMsg() {
      
      retMsg_ = getDefaultInstance().getRetMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string retMsg = 2;</code>
     */
    public Builder setRetMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      retMsg_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object downloadFile_ = "";
    /**
     * <code>string downloadFile = 3;</code>
     */
    public java.lang.String getDownloadFile() {
      java.lang.Object ref = downloadFile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        downloadFile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string downloadFile = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDownloadFileBytes() {
      java.lang.Object ref = downloadFile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        downloadFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string downloadFile = 3;</code>
     */
    public Builder setDownloadFile(
        java.lang.String value) {
      if (value == null) value = "";
  
      downloadFile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string downloadFile = 3;</code>
     */
    public Builder clearDownloadFile() {
      
      downloadFile_ = getDefaultInstance().getDownloadFile();
      onChanged();
      return this;
    }
    /**
     * <code>string downloadFile = 3;</code>
     */
    public Builder setDownloadFileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      downloadFile_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object autoDelete_ = "";
    /**
     * <code>string autoDelete = 4;</code>
     */
    public java.lang.String getAutoDelete() {
      java.lang.Object ref = autoDelete_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        autoDelete_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string autoDelete = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAutoDeleteBytes() {
      java.lang.Object ref = autoDelete_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        autoDelete_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string autoDelete = 4;</code>
     */
    public Builder setAutoDelete(
        java.lang.String value) {
      if (value == null) value = "";
  
      autoDelete_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string autoDelete = 4;</code>
     */
    public Builder clearAutoDelete() {
      
      autoDelete_ = getDefaultInstance().getAutoDelete();
      onChanged();
      return this;
    }
    /**
     * <code>string autoDelete = 4;</code>
     */
    public Builder setAutoDeleteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      autoDelete_ = value;
      onChanged();
      return this;
    }

    private int attachment_ ;
    /**
     * <code>int32 attachment = 5;</code>
     */
    public int getAttachment() {
      return attachment_;
    }
    /**
     * <code>int32 attachment = 5;</code>
     */
    public Builder setAttachment(int value) {
      
      attachment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 attachment = 5;</code>
     */
    public Builder clearAttachment() {
      
      attachment_ = 0;
      onChanged();
      return this;
    }

    private int expire_ ;
    /**
     * <code>int32 expire = 6;</code>
     */
    public int getExpire() {
      return expire_;
    }
    /**
     * <code>int32 expire = 6;</code>
     */
    public Builder setExpire(int value) {
      
      expire_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 expire = 6;</code>
     */
    public Builder clearExpire() {
      
      expire_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString downloadStream_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes downloadStream = 7;</code>
     */
    public com.google.protobuf.ByteString getDownloadStream() {
      return downloadStream_;
    }
    /**
     * <code>bytes downloadStream = 7;</code>
     */
    public Builder setDownloadStream(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      downloadStream_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes downloadStream = 7;</code>
     */
    public Builder clearDownloadStream() {
      
      downloadStream_ = getDefaultInstance().getDownloadStream();
      onChanged();
      return this;
    }

    private java.lang.Object filename_ = "";
    /**
     * <code>string filename = 8;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filename = 8;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filename = 8;</code>
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) value = "";
  
      filename_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string filename = 8;</code>
     */
    public Builder clearFilename() {
      
      filename_ = getDefaultInstance().getFilename();
      onChanged();
      return this;
    }
    /**
     * <code>string filename = 8;</code>
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filename_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HttpDownloadStaticRes)
  }

  // @@protoc_insertion_point(class_scope:HttpDownloadStaticRes)
  private static final com.xxx.userservice.proto.HttpDownloadStaticRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xxx.userservice.proto.HttpDownloadStaticRes();
  }

  public static com.xxx.userservice.proto.HttpDownloadStaticRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HttpDownloadStaticRes>
      PARSER = new com.google.protobuf.AbstractParser<HttpDownloadStaticRes>() {
    @java.lang.Override
    public HttpDownloadStaticRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HttpDownloadStaticRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HttpDownloadStaticRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HttpDownloadStaticRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xxx.userservice.proto.HttpDownloadStaticRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

