// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.xxx.userservice.proto;

public interface HttpPluginTestResOrBuilder extends
        // @@protoc_insertion_point(interface_extends:HttpPluginTestRes)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 retCode = 1;</code>
     */
    int getRetCode();

    /**
     * <code>string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();

    /**
     * <code>string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
    getRetMsgBytes();

    /**
     * <code>string plainText = 3;</code>
     */
    java.lang.String getPlainText();

    /**
     * <code>string plainText = 3;</code>
     */
    com.google.protobuf.ByteString
    getPlainTextBytes();

    /**
     * <code>string redirectUrl = 4;</code>
     */
    java.lang.String getRedirectUrl();

    /**
     * <code>string redirectUrl = 4;</code>
     */
    com.google.protobuf.ByteString
    getRedirectUrlBytes();

    /**
     * <code>string gender = 5;</code>
     */
    java.lang.String getGender();

    /**
     * <code>string gender = 5;</code>
     */
    com.google.protobuf.ByteString
    getGenderBytes();

    /**
     * <code>string mobile = 6;</code>
     */
    java.lang.String getMobile();

    /**
     * <code>string mobile = 6;</code>
     */
    com.google.protobuf.ByteString
    getMobileBytes();

    /**
     * <code>string email = 7;</code>
     */
    java.lang.String getEmail();

    /**
     * <code>string email = 7;</code>
     */
    com.google.protobuf.ByteString
    getEmailBytes();
}
