// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.xxx.userservice.proto;

public interface HttpPluginTestServiceAsync {

    static final public int serviceId = 104;

    java.util.concurrent.CompletableFuture<HttpPluginTestRes> test1(HttpPluginTestReq req);
    static final public int test1MsgId = 1;

    java.util.concurrent.CompletableFuture<HttpDownloadStaticRes> test2(HttpPluginTestReq req);
    static final public int test2MsgId = 2;

    java.util.concurrent.CompletableFuture<HttpUploadTestRes> upload1(HttpUploadTestReq1 req);
    static final public int upload1MsgId = 3;

    java.util.concurrent.CompletableFuture<HttpUploadTestRes> upload2(HttpUploadTestReq2 req);
    static final public int upload2MsgId = 4;

}

