// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.xxx.userservice.proto;

/**
 * Protobuf type {@code HttpUploadTestReq2}
 */
public final class HttpUploadTestReq2 extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:HttpUploadTestReq2)
        HttpUploadTestReq2OrBuilder {
    private static final long serialVersionUID = 0L;

    // Use HttpUploadTestReq2.newBuilder() to construct.
    private HttpUploadTestReq2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private HttpUploadTestReq2() {
        httpContentType_ = "";
        httpContent_ = "";
        a_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        b_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private HttpUploadTestReq2(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        httpContentType_ = s;
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        httpContent_ = s;
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();
                        if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                            a_ = new com.google.protobuf.LazyStringArrayList();
                            mutable_bitField0_ |= 0x00000004;
                        }
                        a_.add(s);
                        break;
                    }
                    case 34: {
                        java.lang.String s = input.readStringRequireUtf8();

                        b_ = s;
                        break;
                    }
                    case 42: {
                        com.xxx.userservice.proto.UploadFile.Builder subBuilder = null;
                        if (files_ != null) {
                            subBuilder = files_.toBuilder();
                        }
                        files_ = input.readMessage(com.xxx.userservice.proto.UploadFile.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(files_);
                            files_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                a_ = a_.getUnmodifiableView();
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.xxx.userservice.proto.UserServiceMetas.internal_static_HttpUploadTestReq2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.xxx.userservice.proto.UserServiceMetas.internal_static_HttpUploadTestReq2_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.xxx.userservice.proto.HttpUploadTestReq2.class, com.xxx.userservice.proto.HttpUploadTestReq2.Builder.class);
    }

    private int bitField0_;
    public static final int HTTPCONTENTTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object httpContentType_;

    /**
     * <code>string httpContentType = 1;</code>
     */
    public java.lang.String getHttpContentType() {
        java.lang.Object ref = httpContentType_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            httpContentType_ = s;
            return s;
        }
    }

    /**
     * <code>string httpContentType = 1;</code>
     */
    public com.google.protobuf.ByteString
    getHttpContentTypeBytes() {
        java.lang.Object ref = httpContentType_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            httpContentType_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int HTTPCONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object httpContent_;

    /**
     * <code>string httpContent = 2;</code>
     */
    public java.lang.String getHttpContent() {
        java.lang.Object ref = httpContent_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            httpContent_ = s;
            return s;
        }
    }

    /**
     * <code>string httpContent = 2;</code>
     */
    public com.google.protobuf.ByteString
    getHttpContentBytes() {
        java.lang.Object ref = httpContent_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            httpContent_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int A_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList a_;

    /**
     * <code>repeated string a = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
    getAList() {
        return a_;
    }

    /**
     * <code>repeated string a = 3;</code>
     */
    public int getACount() {
        return a_.size();
    }

    /**
     * <code>repeated string a = 3;</code>
     */
    public java.lang.String getA(int index) {
        return a_.get(index);
    }

    /**
     * <code>repeated string a = 3;</code>
     */
    public com.google.protobuf.ByteString
    getABytes(int index) {
        return a_.getByteString(index);
    }

    public static final int B_FIELD_NUMBER = 4;
    private volatile java.lang.Object b_;

    /**
     * <code>string b = 4;</code>
     */
    public java.lang.String getB() {
        java.lang.Object ref = b_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            b_ = s;
            return s;
        }
    }

    /**
     * <code>string b = 4;</code>
     */
    public com.google.protobuf.ByteString
    getBBytes() {
        java.lang.Object ref = b_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            b_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int FILES_FIELD_NUMBER = 5;
    private com.xxx.userservice.proto.UploadFile files_;

    /**
     * <code>.UploadFile files = 5;</code>
     */
    public boolean hasFiles() {
        return files_ != null;
    }

    /**
     * <code>.UploadFile files = 5;</code>
     */
    public com.xxx.userservice.proto.UploadFile getFiles() {
        return files_ == null ? com.xxx.userservice.proto.UploadFile.getDefaultInstance() : files_;
    }

    /**
     * <code>.UploadFile files = 5;</code>
     */
    public com.xxx.userservice.proto.UploadFileOrBuilder getFilesOrBuilder() {
        return getFiles();
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getHttpContentTypeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, httpContentType_);
        }
        if (!getHttpContentBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, httpContent_);
        }
        for (int i = 0; i < a_.size(); i++) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, a_.getRaw(i));
        }
        if (!getBBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, b_);
        }
        if (files_ != null) {
            output.writeMessage(5, getFiles());
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getHttpContentTypeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, httpContentType_);
        }
        if (!getHttpContentBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, httpContent_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < a_.size(); i++) {
                dataSize += computeStringSizeNoTag(a_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getAList().size();
        }
        if (!getBBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, b_);
        }
        if (files_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(5, getFiles());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.xxx.userservice.proto.HttpUploadTestReq2)) {
            return super.equals(obj);
        }
        com.xxx.userservice.proto.HttpUploadTestReq2 other = (com.xxx.userservice.proto.HttpUploadTestReq2) obj;

        boolean result = true;
        result = result && getHttpContentType()
                .equals(other.getHttpContentType());
        result = result && getHttpContent()
                .equals(other.getHttpContent());
        result = result && getAList()
                .equals(other.getAList());
        result = result && getB()
                .equals(other.getB());
        result = result && (hasFiles() == other.hasFiles());
        if (hasFiles()) {
            result = result && getFiles()
                    .equals(other.getFiles());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + HTTPCONTENTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getHttpContentType().hashCode();
        hash = (37 * hash) + HTTPCONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getHttpContent().hashCode();
        if (getACount() > 0) {
            hash = (37 * hash) + A_FIELD_NUMBER;
            hash = (53 * hash) + getAList().hashCode();
        }
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + getB().hashCode();
        if (hasFiles()) {
            hash = (37 * hash) + FILES_FIELD_NUMBER;
            hash = (53 * hash) + getFiles().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.xxx.userservice.proto.HttpUploadTestReq2 prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code HttpUploadTestReq2}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:HttpUploadTestReq2)
            com.xxx.userservice.proto.HttpUploadTestReq2OrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.xxx.userservice.proto.UserServiceMetas.internal_static_HttpUploadTestReq2_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.xxx.userservice.proto.UserServiceMetas.internal_static_HttpUploadTestReq2_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.xxx.userservice.proto.HttpUploadTestReq2.class, com.xxx.userservice.proto.HttpUploadTestReq2.Builder.class);
        }

        // Construct using com.xxx.userservice.proto.HttpUploadTestReq2.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            httpContentType_ = "";

            httpContent_ = "";

            a_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000004);
            b_ = "";

            if (filesBuilder_ == null) {
                files_ = null;
            } else {
                files_ = null;
                filesBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.xxx.userservice.proto.UserServiceMetas.internal_static_HttpUploadTestReq2_descriptor;
        }

        @java.lang.Override
        public com.xxx.userservice.proto.HttpUploadTestReq2 getDefaultInstanceForType() {
            return com.xxx.userservice.proto.HttpUploadTestReq2.getDefaultInstance();
        }

        @java.lang.Override
        public com.xxx.userservice.proto.HttpUploadTestReq2 build() {
            com.xxx.userservice.proto.HttpUploadTestReq2 result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.xxx.userservice.proto.HttpUploadTestReq2 buildPartial() {
            com.xxx.userservice.proto.HttpUploadTestReq2 result = new com.xxx.userservice.proto.HttpUploadTestReq2(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.httpContentType_ = httpContentType_;
            result.httpContent_ = httpContent_;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                a_ = a_.getUnmodifiableView();
                bitField0_ = (bitField0_ & ~0x00000004);
            }
            result.a_ = a_;
            result.b_ = b_;
            if (filesBuilder_ == null) {
                result.files_ = files_;
            } else {
                result.files_ = filesBuilder_.build();
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return (Builder) super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.xxx.userservice.proto.HttpUploadTestReq2) {
                return mergeFrom((com.xxx.userservice.proto.HttpUploadTestReq2) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.xxx.userservice.proto.HttpUploadTestReq2 other) {
            if (other == com.xxx.userservice.proto.HttpUploadTestReq2.getDefaultInstance()) return this;
            if (!other.getHttpContentType().isEmpty()) {
                httpContentType_ = other.httpContentType_;
                onChanged();
            }
            if (!other.getHttpContent().isEmpty()) {
                httpContent_ = other.httpContent_;
                onChanged();
            }
            if (!other.a_.isEmpty()) {
                if (a_.isEmpty()) {
                    a_ = other.a_;
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    ensureAIsMutable();
                    a_.addAll(other.a_);
                }
                onChanged();
            }
            if (!other.getB().isEmpty()) {
                b_ = other.b_;
                onChanged();
            }
            if (other.hasFiles()) {
                mergeFiles(other.getFiles());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.xxx.userservice.proto.HttpUploadTestReq2 parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.xxx.userservice.proto.HttpUploadTestReq2) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private java.lang.Object httpContentType_ = "";

        /**
         * <code>string httpContentType = 1;</code>
         */
        public java.lang.String getHttpContentType() {
            java.lang.Object ref = httpContentType_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                httpContentType_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string httpContentType = 1;</code>
         */
        public com.google.protobuf.ByteString
        getHttpContentTypeBytes() {
            java.lang.Object ref = httpContentType_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                httpContentType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string httpContentType = 1;</code>
         */
        public Builder setHttpContentType(
                java.lang.String value) {
            if (value == null) value = "";

            httpContentType_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string httpContentType = 1;</code>
         */
        public Builder clearHttpContentType() {

            httpContentType_ = getDefaultInstance().getHttpContentType();
            onChanged();
            return this;
        }

        /**
         * <code>string httpContentType = 1;</code>
         */
        public Builder setHttpContentTypeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            httpContentType_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object httpContent_ = "";

        /**
         * <code>string httpContent = 2;</code>
         */
        public java.lang.String getHttpContent() {
            java.lang.Object ref = httpContent_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                httpContent_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string httpContent = 2;</code>
         */
        public com.google.protobuf.ByteString
        getHttpContentBytes() {
            java.lang.Object ref = httpContent_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                httpContent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string httpContent = 2;</code>
         */
        public Builder setHttpContent(
                java.lang.String value) {
            if (value == null) value = "";

            httpContent_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string httpContent = 2;</code>
         */
        public Builder clearHttpContent() {

            httpContent_ = getDefaultInstance().getHttpContent();
            onChanged();
            return this;
        }

        /**
         * <code>string httpContent = 2;</code>
         */
        public Builder setHttpContentBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            httpContent_ = value;
            onChanged();
            return this;
        }

        private com.google.protobuf.LazyStringList a_ = com.google.protobuf.LazyStringArrayList.EMPTY;

        private void ensureAIsMutable() {
            if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                a_ = new com.google.protobuf.LazyStringArrayList(a_);
                bitField0_ |= 0x00000004;
            }
        }

        /**
         * <code>repeated string a = 3;</code>
         */
        public com.google.protobuf.ProtocolStringList
        getAList() {
            return a_.getUnmodifiableView();
        }

        /**
         * <code>repeated string a = 3;</code>
         */
        public int getACount() {
            return a_.size();
        }

        /**
         * <code>repeated string a = 3;</code>
         */
        public java.lang.String getA(int index) {
            return a_.get(index);
        }

        /**
         * <code>repeated string a = 3;</code>
         */
        public com.google.protobuf.ByteString
        getABytes(int index) {
            return a_.getByteString(index);
        }

        /**
         * <code>repeated string a = 3;</code>
         */
        public Builder setA(
                int index, java.lang.String value) {
            if (value == null) value = "";
            ensureAIsMutable();
            a_.set(index, value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string a = 3;</code>
         */
        public Builder addA(
                java.lang.String value) {
            if (value == null) value = "";
            ensureAIsMutable();
            a_.add(value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string a = 3;</code>
         */
        public Builder addAllA(
                java.lang.Iterable<java.lang.String> values) {
            ensureAIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, a_);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string a = 3;</code>
         */
        public Builder clearA() {
            a_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string a = 3;</code>
         */
        public Builder addABytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureAIsMutable();
            a_.add(value);
            onChanged();
            return this;
        }

        private java.lang.Object b_ = "";

        /**
         * <code>string b = 4;</code>
         */
        public java.lang.String getB() {
            java.lang.Object ref = b_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                b_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string b = 4;</code>
         */
        public com.google.protobuf.ByteString
        getBBytes() {
            java.lang.Object ref = b_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                b_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string b = 4;</code>
         */
        public Builder setB(
                java.lang.String value) {
            if (value == null) value = "";

            b_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string b = 4;</code>
         */
        public Builder clearB() {

            b_ = getDefaultInstance().getB();
            onChanged();
            return this;
        }

        /**
         * <code>string b = 4;</code>
         */
        public Builder setBBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            b_ = value;
            onChanged();
            return this;
        }

        private com.xxx.userservice.proto.UploadFile files_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                com.xxx.userservice.proto.UploadFile, com.xxx.userservice.proto.UploadFile.Builder, com.xxx.userservice.proto.UploadFileOrBuilder> filesBuilder_;

        /**
         * <code>.UploadFile files = 5;</code>
         */
        public boolean hasFiles() {
            return filesBuilder_ != null || files_ != null;
        }

        /**
         * <code>.UploadFile files = 5;</code>
         */
        public com.xxx.userservice.proto.UploadFile getFiles() {
            if (filesBuilder_ == null) {
                return files_ == null ? com.xxx.userservice.proto.UploadFile.getDefaultInstance() : files_;
            } else {
                return filesBuilder_.getMessage();
            }
        }

        /**
         * <code>.UploadFile files = 5;</code>
         */
        public Builder setFiles(com.xxx.userservice.proto.UploadFile value) {
            if (filesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                files_ = value;
                onChanged();
            } else {
                filesBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.UploadFile files = 5;</code>
         */
        public Builder setFiles(
                com.xxx.userservice.proto.UploadFile.Builder builderForValue) {
            if (filesBuilder_ == null) {
                files_ = builderForValue.build();
                onChanged();
            } else {
                filesBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.UploadFile files = 5;</code>
         */
        public Builder mergeFiles(com.xxx.userservice.proto.UploadFile value) {
            if (filesBuilder_ == null) {
                if (files_ != null) {
                    files_ =
                            com.xxx.userservice.proto.UploadFile.newBuilder(files_).mergeFrom(value).buildPartial();
                } else {
                    files_ = value;
                }
                onChanged();
            } else {
                filesBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.UploadFile files = 5;</code>
         */
        public Builder clearFiles() {
            if (filesBuilder_ == null) {
                files_ = null;
                onChanged();
            } else {
                files_ = null;
                filesBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.UploadFile files = 5;</code>
         */
        public com.xxx.userservice.proto.UploadFile.Builder getFilesBuilder() {

            onChanged();
            return getFilesFieldBuilder().getBuilder();
        }

        /**
         * <code>.UploadFile files = 5;</code>
         */
        public com.xxx.userservice.proto.UploadFileOrBuilder getFilesOrBuilder() {
            if (filesBuilder_ != null) {
                return filesBuilder_.getMessageOrBuilder();
            } else {
                return files_ == null ?
                        com.xxx.userservice.proto.UploadFile.getDefaultInstance() : files_;
            }
        }

        /**
         * <code>.UploadFile files = 5;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                com.xxx.userservice.proto.UploadFile, com.xxx.userservice.proto.UploadFile.Builder, com.xxx.userservice.proto.UploadFileOrBuilder>
        getFilesFieldBuilder() {
            if (filesBuilder_ == null) {
                filesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        com.xxx.userservice.proto.UploadFile, com.xxx.userservice.proto.UploadFile.Builder, com.xxx.userservice.proto.UploadFileOrBuilder>(
                        getFiles(),
                        getParentForChildren(),
                        isClean());
                files_ = null;
            }
            return filesBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:HttpUploadTestReq2)
    }

    // @@protoc_insertion_point(class_scope:HttpUploadTestReq2)
    private static final com.xxx.userservice.proto.HttpUploadTestReq2 DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.xxx.userservice.proto.HttpUploadTestReq2();
    }

    public static com.xxx.userservice.proto.HttpUploadTestReq2 getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HttpUploadTestReq2>
            PARSER = new com.google.protobuf.AbstractParser<HttpUploadTestReq2>() {
        @java.lang.Override
        public HttpUploadTestReq2 parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new HttpUploadTestReq2(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<HttpUploadTestReq2> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HttpUploadTestReq2> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.xxx.userservice.proto.HttpUploadTestReq2 getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

