// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.xxx.userservice.proto;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderId = 1;</code>
   */
  java.lang.String getOrderId();
  /**
   * <code>string orderId = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>int32 amount = 2;</code>
   */
  int getAmount();

  /**
   * <code>.Session session = 3;</code>
   */
  boolean hasSession();
  /**
   * <code>.Session session = 3;</code>
   */
  com.xxx.userservice.proto.Session getSession();
  /**
   * <code>.Session session = 3;</code>
   */
  com.xxx.userservice.proto.SessionOrBuilder getSessionOrBuilder();

  /**
   * <code>repeated .OrderItem items = 4;</code>
   */
  java.util.List<com.xxx.userservice.proto.OrderItem> 
      getItemsList();
  /**
   * <code>repeated .OrderItem items = 4;</code>
   */
  com.xxx.userservice.proto.OrderItem getItems(int index);
  /**
   * <code>repeated .OrderItem items = 4;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .OrderItem items = 4;</code>
   */
  java.util.List<? extends com.xxx.userservice.proto.OrderItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .OrderItem items = 4;</code>
   */
  com.xxx.userservice.proto.OrderItemOrBuilder getItemsOrBuilder(
      int index);
}
