// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.xxx.userservice.proto;

public interface OrderDetailOrBuilder extends
        // @@protoc_insertion_point(interface_extends:OrderDetail)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>int32 quantity = 2;</code>
     */
    int getQuantity();

    /**
     * <code>double price = 3;</code>
     */
    double getPrice();

    /**
     * <code>string note = 4;</code>
     */
    java.lang.String getNote();

    /**
     * <code>string note = 4;</code>
     */
    com.google.protobuf.ByteString
    getNoteBytes();
}
