// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.xxx.userservice.proto;

public interface ValidateSubOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ValidateSub)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string s1 = 11 [(.krpc.vld) = { ... }</code>
   */
  String getS1();
  /**
   * <code>string s1 = 11 [(.krpc.vld) = { ... }</code>
   */
  com.google.protobuf.ByteString
      getS1Bytes();

  /**
   * <code>string s2 = 14 [(.krpc.vld) = { ... }</code>
   */
  String getS2();
  /**
   * <code>string s2 = 14 [(.krpc.vld) = { ... }</code>
   */
  com.google.protobuf.ByteString
      getS2Bytes();

  /**
   * <code>int32 i1 = 15 [(.krpc.vld) = { ... }</code>
   */
  int getI1();

  /**
   * <code>string i2 = 16 [(.krpc.vld) = { ... }</code>
   */
  String getI2();
  /**
   * <code>string i2 = 16 [(.krpc.vld) = { ... }</code>
   */
  com.google.protobuf.ByteString
      getI2Bytes();

  /**
   * <code>int32 i3 = 17 [(.krpc.vld) = { ... }</code>
   */
  int getI3();

  /**
   * <code>string i4 = 18 [(.krpc.vld) = { ... }</code>
   */
  String getI4();
  /**
   * <code>string i4 = 18 [(.krpc.vld) = { ... }</code>
   */
  com.google.protobuf.ByteString
      getI4Bytes();
}
