// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.xxx.userservice.proto;

public interface ValidateTestResOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ValidateTestRes)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 retCode = 1;</code>
     */
    int getRetCode();
}
