// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.xxx.userservice.proto;

public interface PushServicev2 {

    static final public int serviceId = 103;

    com.xxx.userservice.proto.PushRes pushv2(com.xxx.userservice.proto.PushReq req);
    static final public int pushv2MsgId = 1;

}

