// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.xxx.userservice.proto;

public final class UserServiceMetas {
  private UserServiceMetas() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateProfileReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateProfileReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateProfileRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateProfileRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderItemAttr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderItemAttr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021userservice.proto\032\rkrpcext.proto\".\n\010Lo" +
      "ginReq\022\020\n\010userName\030\001 \001(\t\022\020\n\010password\030\002 \001" +
      "(\t\";\n\010LoginRes\022\017\n\007retCode\030\001 \001(\005\022\016\n\006retMs" +
      "g\030\002 \001(\t\022\016\n\006userId\030\003 \001(\t\"2\n\020UpdateProfile" +
      "Req\022\016\n\006userId\030\001 \001(\t\022\016\n\006mobile\030\002 \001(\t\"3\n\020U" +
      "pdateProfileRes\022\017\n\007retCode\030\001 \001(\005\022\016\n\006retM" +
      "sg\030\002 \001(\t\",\n\rOrderItemAttr\022\014\n\004name\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t\"W\n\tOrderItem\022\016\n\006itemId\030\001 " +
      "\001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005price\030\003 \001(\005\022\035\n\005attr" +
      "s\030\004 \003(\0132\016.OrderItemAttr\"3\n\005Order\022\017\n\007orde" +
      "rId\030\001 \001(\t\022\031\n\005items\030\002 \003(\0132\n.OrderItem2r\n\013" +
      "UserService\022\"\n\005login\022\t.LoginReq\032\t.LoginR" +
      "es\"\003\320>\001\022:\n\rupdateProfile\022\021.UpdateProfile" +
      "Req\032\021.UpdateProfileRes\"\003\320>\002\032\003\310>dB2\n\031com." +
      "xxx.userservice.protoB\020UserServiceMetasP" +
      "\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          krpc.KrpcExt.getDescriptor(),
        }, assigner);
    internal_static_LoginReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginReq_descriptor,
        new java.lang.String[] { "UserName", "Password", });
    internal_static_LoginRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRes_descriptor,
        new java.lang.String[] { "RetCode", "RetMsg", "UserId", });
    internal_static_UpdateProfileReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UpdateProfileReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateProfileReq_descriptor,
        new java.lang.String[] { "UserId", "Mobile", });
    internal_static_UpdateProfileRes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateProfileRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateProfileRes_descriptor,
        new java.lang.String[] { "RetCode", "RetMsg", });
    internal_static_OrderItemAttr_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OrderItemAttr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderItemAttr_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_OrderItem_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OrderItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderItem_descriptor,
        new java.lang.String[] { "ItemId", "Name", "Price", "Attrs", });
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "OrderId", "Items", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(krpc.KrpcExt.msgId);
    registry.add(krpc.KrpcExt.serviceId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    krpc.KrpcExt.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
